### ISSUE TITLE
Identify and prevent possible data race conditions.

### ISSUE THREAD

**Issue by burntcarrot** [burntcarrot/octopool#1]
octopool's emphasis is on reliability, and since data race conditions reduce reliability, this issue's scope is to prevent possible data race conditions.

**Who can take this up:**
Anyone. Some prior experience with the race detector is recommended.

**Comment by burntcarrot** [comment]
This issue is also eligible for Hacktoberfest 2021. Feel free to make a PR, contributions are welcome! 😄

**Comment by DGKSK8LIFE** [comment]
Please assign me to this issue!

**Comment by burntcarrot** [comment]
Thank you for showing interest @DGKSK8LIFE! Will be waiting for your PR! 😄

**Comment by burntcarrot** [comment]
@DGKSK8LIFE Would you like to unassign yourself from this issue, if you're not interested or if you're busy?

I'm thinking that others would love to help on out this issue.

**Comment by DGKSK8LIFE** [comment]
Yeah you can if you'd like. I identified a few potential (especially those interacting with WaitGroup and channels), but patching/altering them would alter the code greatly and not produce a desired end result I think.
